# Generated by Django 3.1.7 on 2021-08-13 08:42

import decoder.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PdfFiles',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=30, verbose_name='Логин')),
                ('inn', models.CharField(max_length=10, verbose_name='ИНН')),
                ('pdf_file', models.FileField(upload_to=decoder.models.content_file_name)),
                ('file_name', models.CharField(max_length=200, verbose_name='Название файла')),
                ('csv_file', models.CharField(max_length=250, verbose_name='csv файл')),
                ('pdf_file_link', models.CharField(max_length=250, verbose_name='pdf файл')),
                ('count_pages', models.IntegerField(verbose_name='Количество км')),
                ('data', models.DateTimeField(auto_now_add=True)),
                ('arg1', models.CharField(blank=True, max_length=250)),
                ('arg2', models.CharField(blank=True, max_length=250)),
                ('arg3', models.CharField(blank=True, max_length=250)),
                ('arg4', models.CharField(blank=True, max_length=250)),
                ('arg5', models.CharField(blank=True, max_length=250)),
            ],
        ),
    ]
