# Generated by Django 3.1.7 on 2021-08-13 08:42

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data', models.DateTimeField(auto_now_add=True)),
                ('author', models.CharField(max_length=20, verbose_name='Автор')),
                ('tel', models.CharField(max_length=14, verbose_name='Телефон')),
                ('text', models.TextField(verbose_name='Комментарий')),
                ('arg1', models.CharField(blank=True, max_length=250)),
                ('arg2', models.CharField(blank=True, max_length=250)),
                ('arg3', models.CharField(blank=True, max_length=250)),
                ('arg4', models.CharField(blank=True, max_length=250)),
                ('arg5', models.CharField(blank=True, max_length=250)),
            ],
        ),
    ]
