# Generated by Django 3.1.7 on 2021-08-13 08:42

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Personal',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=30, verbose_name='Логин')),
                ('inn', models.CharField(max_length=10, verbose_name='ИНН')),
                ('balance', models.DecimalField(decimal_places=2, max_digits=9, verbose_name='Баланс')),
                ('prefix', models.CharField(max_length=10, verbose_name='Префикс компании gs1')),
                ('arg1', models.CharField(blank=True, max_length=250)),
                ('arg2', models.CharField(blank=True, max_length=250)),
                ('arg3', models.CharField(blank=True, max_length=250)),
                ('arg4', models.CharField(blank=True, max_length=250)),
                ('arg5', models.CharField(blank=True, max_length=250)),
            ],
        ),
        migrations.CreateModel(
            name='Transactions',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data', models.DateTimeField(auto_now_add=True)),
                ('inn', models.CharField(max_length=10, verbose_name='ИНН')),
                ('sum', models.DecimalField(decimal_places=2, max_digits=9, verbose_name='Сумма операции')),
                ('comment', models.CharField(blank=True, max_length=200, verbose_name='Комментарий')),
                ('arg1', models.CharField(blank=True, max_length=250)),
                ('arg2', models.CharField(blank=True, max_length=250)),
                ('arg3', models.CharField(blank=True, max_length=250)),
                ('arg4', models.CharField(blank=True, max_length=250)),
                ('arg5', models.CharField(blank=True, max_length=250)),
            ],
        ),
    ]
